# GitHub Actions Runner Controller (ARC) Helm Chart Values
# Deploy ARC controller to arc-systems namespace

# Override the default namespace
namespaceOverride: arc-systems

# GitHub configuration
githubConfigUrl: "https://github.com/amerenda"

# Install CRDs automatically
installCRDs: true

# GitHub authentication - ARC expects secret named 'controller-manager'

# Controller configuration
controller:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/actions/actions-runner-controller
    tag: v0.8.1
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Service account
  serviceAccount:
    create: true
    name: arc-controller
    annotations: {}

  # RBAC configuration
  rbac:
    create: true

  # Pod security policy
  podSecurityPolicy:
    enabled: false

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Pod annotations
  podAnnotations: {}

  # Pod labels
  podLabels: {}

  # Service annotations
  serviceAnnotations: {}

  # Service labels
  serviceLabels: {}

  # Extra arguments
  extraArgs: []

  # Extra environment variables
  extraEnv: []

  # Pod disruption budget
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: 1

# Webhook configuration
webhook:
  enabled: true
  port: 9443
  certificate:
    create: true
    duration: 8760h # 1 year
    renewBefore: 360h # 15 days

# Metrics configuration
metrics:
  enabled: false
  serviceMonitor:
    enabled: false

# Logging configuration
logLevel: info

# Leader election
leaderElection:
  enabled: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
