apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-access-token
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: home-assistant-access-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: home-assistant-access-token
      property: token

