#!/bin/bash

# Script to generate per-room schedule input helpers
# Usage: ./generate-room-schedules.sh

set -e

ROOMS=("living_room" "kitchen" "bedroom" "bathroom" "hallway")
OUTPUT_FILE="config/room_schedule_inputs.yaml"

echo "Generating per-room schedule input helpers..."

# Start the room schedule inputs YAML
cat > "$OUTPUT_FILE" << EOF
# Per-room schedule input helpers
# Generated automatically - do not edit manually

EOF

# Generate input_boolean section
echo "input_boolean:" >> "$OUTPUT_FILE"
for room in "${ROOMS[@]}"; do
    room_display=$(echo "$room" | sed 's/_/ /g' | sed 's/\b\w/\U&/g')
    
    echo "  ${room}_schedule_enabled:" >> "$OUTPUT_FILE"
    echo "    name: \"Enable $room_display Schedule\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:clock-outline" >> "$OUTPUT_FILE"
    echo "    initial: true" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

# Generate input_datetime section
echo "input_datetime:" >> "$OUTPUT_FILE"
for room in "${ROOMS[@]}"; do
    room_display=$(echo "$room" | sed 's/_/ /g' | sed 's/\b\w/\U&/g')
    
    echo "  ${room}_schedule_1_start:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Morning Start\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunrise" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"06:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_1_end:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Morning End\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunny" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"09:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_2_start:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Day Start\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunny" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"09:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_2_end:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Day End\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunset" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"17:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_3_start:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Evening Start\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunset" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"17:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_3_end:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Evening End\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-night" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"21:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_4_start:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Night Start\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-night" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"21:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_4_end:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Night End\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-night" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"23:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_5_start:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Late Night Start\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-night" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"23:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_5_end:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Late Night End\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunrise" >> "$OUTPUT_FILE"
    echo "    has_time: true" >> "$OUTPUT_FILE"
    echo "    has_date: false" >> "$OUTPUT_FILE"
    echo "    initial: \"06:00\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

# Generate input_select section
echo "input_select:" >> "$OUTPUT_FILE"
for room in "${ROOMS[@]}"; do
    room_display=$(echo "$room" | sed 's/_/ /g' | sed 's/\b\w/\U&/g')
    
    echo "  ${room}_schedule_1_scene:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Morning Scene\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunrise" >> "$OUTPUT_FILE"
    echo "    options:" >> "$OUTPUT_FILE"
    echo "      - \"energize\"" >> "$OUTPUT_FILE"
    echo "      - \"concentrate\"" >> "$OUTPUT_FILE"
    echo "      - \"relax\"" >> "$OUTPUT_FILE"
    echo "      - \"nightlight\"" >> "$OUTPUT_FILE"
    echo "      - \"read\"" >> "$OUTPUT_FILE"
    echo "      - \"dimmed\"" >> "$OUTPUT_FILE"
    echo "    initial: \"energize\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_2_scene:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Day Scene\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunny" >> "$OUTPUT_FILE"
    echo "    options:" >> "$OUTPUT_FILE"
    echo "      - \"energize\"" >> "$OUTPUT_FILE"
    echo "      - \"concentrate\"" >> "$OUTPUT_FILE"
    echo "      - \"relax\"" >> "$OUTPUT_FILE"
    echo "      - \"nightlight\"" >> "$OUTPUT_FILE"
    echo "      - \"read\"" >> "$OUTPUT_FILE"
    echo "      - \"dimmed\"" >> "$OUTPUT_FILE"
    echo "    initial: \"concentrate\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_3_scene:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Evening Scene\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-sunset" >> "$OUTPUT_FILE"
    echo "    options:" >> "$OUTPUT_FILE"
    echo "      - \"energize\"" >> "$OUTPUT_FILE"
    echo "      - \"concentrate\"" >> "$OUTPUT_FILE"
    echo "      - \"relax\"" >> "$OUTPUT_FILE"
    echo "      - \"nightlight\"" >> "$OUTPUT_FILE"
    echo "      - \"read\"" >> "$OUTPUT_FILE"
    echo "      - \"dimmed\"" >> "$OUTPUT_FILE"
    echo "    initial: \"relax\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_4_scene:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Night Scene\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-night" >> "$OUTPUT_FILE"
    echo "    options:" >> "$OUTPUT_FILE"
    echo "      - \"energize\"" >> "$OUTPUT_FILE"
    echo "      - \"concentrate\"" >> "$OUTPUT_FILE"
    echo "      - \"relax\"" >> "$OUTPUT_FILE"
    echo "      - \"nightlight\"" >> "$OUTPUT_FILE"
    echo "      - \"read\"" >> "$OUTPUT_FILE"
    echo "      - \"dimmed\"" >> "$OUTPUT_FILE"
    echo "    initial: \"nightlight\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_schedule_5_scene:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Late Night Scene\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:weather-night" >> "$OUTPUT_FILE"
    echo "    options:" >> "$OUTPUT_FILE"
    echo "      - \"energize\"" >> "$OUTPUT_FILE"
    echo "      - \"concentrate\"" >> "$OUTPUT_FILE"
    echo "      - \"relax\"" >> "$OUTPUT_FILE"
    echo "      - \"nightlight\"" >> "$OUTPUT_FILE"
    echo "      - \"read\"" >> "$OUTPUT_FILE"
    echo "      - \"dimmed\"" >> "$OUTPUT_FILE"
    echo "    initial: \"nightlight\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "  ${room}_default_scene:" >> "$OUTPUT_FILE"
    echo "    name: \"$room_display Default Scene\"" >> "$OUTPUT_FILE"
    echo "    icon: mdi:lightbulb" >> "$OUTPUT_FILE"
    echo "    options:" >> "$OUTPUT_FILE"
    echo "      - \"energize\"" >> "$OUTPUT_FILE"
    echo "      - \"concentrate\"" >> "$OUTPUT_FILE"
    echo "      - \"relax\"" >> "$OUTPUT_FILE"
    echo "      - \"nightlight\"" >> "$OUTPUT_FILE"
    echo "      - \"read\"" >> "$OUTPUT_FILE"
    echo "      - \"dimmed\"" >> "$OUTPUT_FILE"
    echo "    initial: \"relax\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo "Room schedule inputs generated: $OUTPUT_FILE"
echo "To apply: run ./generate-automations-configmap.sh and commit the changes"