apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-helpers-input-select
data:
  bathroom.yaml: |
    # Template for input_select helpers per room
    # Usage:
    #   jinja2 input_select_template.yaml.j2 -D room=bedroom > input_select/bedroom.yaml
    
    bathroom_morning_scene:
      name: Bathroom Morning scene
      options:
        - scene.bathroom_morning
        - scene.bathroom_day
        - scene.bathroom_evening
        - scene.bathroom_night
      initial: scene.bathroom_morning
    bathroom_day_scene:
      name: Bathroom Day scene
      options:
        - scene.bathroom_day
        - scene.bathroom_morning
        - scene.bathroom_evening
        - scene.bathroom_night
      initial: scene.bathroom_day
    bathroom_evening_scene:
      name: Bathroom Evening scene
      options:
        - scene.bathroom_evening
        - scene.bathroom_day
        - scene.bathroom_morning
        - scene.bathroom_night
      initial: scene.bathroom_evening
    bathroom_night_scene:
      name: Bathroom Night scene
      options:
        - scene.bathroom_night
        - scene.bathroom_evening
        - scene.bathroom_day
        - scene.bathroom_morning
      initial: scene.bathroom_night
    
    bathroom_scene_cycle:
      name: Bathroom Scene Cycle
      options:
        - morning
        - day
        - evening
        - night
      initial: morning
  bedroom.yaml: |
    # Template for input_select helpers per room
    # Usage:
    #   jinja2 input_select_template.yaml.j2 -D room=bedroom > input_select/bedroom.yaml
    
    bedroom_morning_scene:
      name: Bedroom Morning scene
      options:
        - scene.bedroom_morning
        - scene.bedroom_day
        - scene.bedroom_evening
        - scene.bedroom_night
      initial: scene.bedroom_morning
    bedroom_day_scene:
      name: Bedroom Day scene
      options:
        - scene.bedroom_day
        - scene.bedroom_morning
        - scene.bedroom_evening
        - scene.bedroom_night
      initial: scene.bedroom_day
    bedroom_evening_scene:
      name: Bedroom Evening scene
      options:
        - scene.bedroom_evening
        - scene.bedroom_day
        - scene.bedroom_morning
        - scene.bedroom_night
      initial: scene.bedroom_evening
    bedroom_night_scene:
      name: Bedroom Night scene
      options:
        - scene.bedroom_night
        - scene.bedroom_evening
        - scene.bedroom_day
        - scene.bedroom_morning
      initial: scene.bedroom_night
    
    bedroom_scene_cycle:
      name: Bedroom Scene Cycle
      options:
        - morning
        - day
        - evening
        - night
      initial: morning
  hallway.yaml: |
    # Template for input_select helpers per room
    # Usage:
    #   jinja2 input_select_template.yaml.j2 -D room=bedroom > input_select/bedroom.yaml
    
    hallway_morning_scene:
      name: Hallway Morning scene
      options:
        - scene.hallway_morning
        - scene.hallway_day
        - scene.hallway_evening
        - scene.hallway_night
      initial: scene.hallway_morning
    hallway_day_scene:
      name: Hallway Day scene
      options:
        - scene.hallway_day
        - scene.hallway_morning
        - scene.hallway_evening
        - scene.hallway_night
      initial: scene.hallway_day
    hallway_evening_scene:
      name: Hallway Evening scene
      options:
        - scene.hallway_evening
        - scene.hallway_day
        - scene.hallway_morning
        - scene.hallway_night
      initial: scene.hallway_evening
    hallway_night_scene:
      name: Hallway Night scene
      options:
        - scene.hallway_night
        - scene.hallway_evening
        - scene.hallway_day
        - scene.hallway_morning
      initial: scene.hallway_night
    
    hallway_scene_cycle:
      name: Hallway Scene Cycle
      options:
        - morning
        - day
        - evening
        - night
      initial: morning
  kitchen.yaml: |
    # Template for input_select helpers per room
    # Usage:
    #   jinja2 input_select_template.yaml.j2 -D room=bedroom > input_select/bedroom.yaml
    
    kitchen_morning_scene:
      name: Kitchen Morning scene
      options:
        - scene.kitchen_morning
        - scene.kitchen_day
        - scene.kitchen_evening
        - scene.kitchen_night
      initial: scene.kitchen_morning
    kitchen_day_scene:
      name: Kitchen Day scene
      options:
        - scene.kitchen_day
        - scene.kitchen_morning
        - scene.kitchen_evening
        - scene.kitchen_night
      initial: scene.kitchen_day
    kitchen_evening_scene:
      name: Kitchen Evening scene
      options:
        - scene.kitchen_evening
        - scene.kitchen_day
        - scene.kitchen_morning
        - scene.kitchen_night
      initial: scene.kitchen_evening
    kitchen_night_scene:
      name: Kitchen Night scene
      options:
        - scene.kitchen_night
        - scene.kitchen_evening
        - scene.kitchen_day
        - scene.kitchen_morning
      initial: scene.kitchen_night
    
    kitchen_scene_cycle:
      name: Kitchen Scene Cycle
      options:
        - morning
        - day
        - evening
        - night
      initial: morning
  living_room.yaml: |
    # Template for input_select helpers per room
    # Usage:
    #   jinja2 input_select_template.yaml.j2 -D room=bedroom > input_select/bedroom.yaml
    
    living_room_morning_scene:
      name: Living Room Morning scene
      options:
        - scene.living_room_morning
        - scene.living_room_day
        - scene.living_room_evening
        - scene.living_room_night
      initial: scene.living_room_morning
    living_room_day_scene:
      name: Living Room Day scene
      options:
        - scene.living_room_day
        - scene.living_room_morning
        - scene.living_room_evening
        - scene.living_room_night
      initial: scene.living_room_day
    living_room_evening_scene:
      name: Living Room Evening scene
      options:
        - scene.living_room_evening
        - scene.living_room_day
        - scene.living_room_morning
        - scene.living_room_night
      initial: scene.living_room_evening
    living_room_night_scene:
      name: Living Room Night scene
      options:
        - scene.living_room_night
        - scene.living_room_evening
        - scene.living_room_day
        - scene.living_room_morning
      initial: scene.living_room_night
    
    living_room_scene_cycle:
      name: Living Room Scene Cycle
      options:
        - morning
        - day
        - evening
        - night
      initial: morning
  room_selector.yaml: |
    room_selector:
      name: Room Selector
      options:
        - bathroom
        - bedroom
        - hallway
        - kitchen
        - living_room
      initial: bathroom
    
