---
# Bitwarden SecretStore Configuration
# This SecretStore connects External Secrets Operator to Bitwarden Secrets Manager
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretstore
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    bitwardensecretsmanager:
      # Bitwarden API configuration
      apiURL: "https://api.bitwarden.com"
      identityURL: "https://identity.bitwarden.com"
      # Organization and Project IDs
      organizationID: "a9b83b36-d37e-4532-88a4-b36f00df7f3d"
      projectID: "6353f589-39c0-45f2-9e9c-b36f00e0c282"
      # Bitwarden SDK Server URL
      bitwardenServerSDKURL: "https://bitwarden-sdk-server.default.svc.cluster.local:9998"
      # CA Provider for TLS - reference the generated certificate
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: default
        key: ca.crt
      # Authentication using machine account token
      auth:
        secretRef:
          credentials:
            key: access-token
            name: bitwarden-credentials
            namespace: default
 