---
# Bitwarden SecretStore Configuration Template
# This SecretStore connects External Secrets Operator to Bitwarden Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bitwarden-secretstore
  namespace: external-secrets
spec:
  provider:
    bitwarden:
      server: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      
      auth:
        secretRef:
          accessTokenSecretRef:
            name: bitwarden-credentials
            key: access-token
 