# eufy-ws-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eufy-ws-data
  namespace: home-automation
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path