# yamllint configuration for Home Assistant YAML files
# Based on Home Assistant's recommended yamllint settings

extends: default

rules:
  # Allow longer lines for Home Assistant configurations
  line-length:
    max: 120
    level: warning
  
  # Allow comments at end of line
  comments:
    min-spaces-from-content: 1
  
  # Allow indentation with 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  # Allow truthy values (yes/no, on/off, etc.)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false
  
  # Allow brackets in flow style
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  
  # Allow braces in flow style
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  
  # Allow commas at end of lines
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  
  # Allow colons in flow style
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  
  # Allow hyphens in list items
  hyphens:
    max-spaces-after: 1
  
  # Allow trailing spaces (sometimes needed for YAML)
  trailing-spaces:
    level: warning
  
  # Allow empty lines at end of file
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  
  # Allow document start
  document-start:
    present: false
  
  # Allow document end
  document-end:
    present: false
  
  # Allow quoted strings
  quoted-strings:
    quote-type: any
    check-keys: false
  
  # Allow octal values
  octal-values:
    forbid-implicit-octal: false
