apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bind9-tsig
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: bind9-tsig
    creationPolicy: Owner
  data:
  - secretKey: key.conf
    remoteRef:
      key: bind9-tsig-key
      property: key.conf
