apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.20.241
  selector:
    app: bind9
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
