apiVersion: v1
kind: Secret
metadata:
  name: ghcr-actions-runner-controller-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  # For public OCI registries, username and password can be empty
  # ArgoCD will use anonymous access for public registries
  username: ""
  password: ""

