apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: arc-runners
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Install before runner scale set
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: controller-manager
    creationPolicy: Owner
  data:
  - secretKey: github_app_id
    remoteRef:
      key: github-app-arc-id
      property: github_app_id
  - secretKey: github_app_installation_id
    remoteRef:
      key: github-app-arc-installation-id
      property: github_app_installation_id
  - secretKey: github_app_private_key
    remoteRef:
      key: github-app-arc-private-key
      property: github_app_private_key

