apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: arc-runner-set
  namespace: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  # GitHub configuration - organization-wide
  organization: amerenda
  githubAPICredentialsFrom:
    secretRef:
      name: controller-manager
  
  # Runner image
  image: ghcr.io/actions/actions-runner:latest
  
  # Runner labels (must match runs-on in workflows)
  labels:
    - self-hosted
    - linux
    - arc-runner-set
  
  # Docker configuration for container jobs
  dockerdWithinRunnerContainer: true
  dockerEnabled: true
  
  # Replica configuration - start with 0, scale up on demand
  replicas: 0
  
  # Service name (required)
  serviceName: arc-runner-set
  
  # Selector (required)
  selector:
    matchLabels:
      runner-template: arc-runner-set
  
  # Pod template
  template:
    metadata:
      labels:
        runner-template: arc-runner-set
    spec:
      # Service account
      serviceAccountName: arc-runner-set
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      # Containers
      containers:
      - name: runner
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
