apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner-set
  namespace: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Before RunnerSet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-set
  namespace: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "4"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-set
  namespace: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-set
subjects:
- kind: ServiceAccount
  name: arc-runner-set
  namespace: arc-systems
