# GitHub Actions Runner Scale Set Helm Chart Values
# Deploy ARC runner scale set to arc-runners namespace
# Based on: https://docs.github.com/en/actions/tutorials/use-actions-runner-controller/quickstart

# GitHub configuration - repository-level (required for personal accounts)
githubConfigUrl: "https://github.com/amerenda/amerenda-k3s"

# Runner scale set name (used as runs-on in workflows)
# This must match the runs-on label in GitHub Actions workflows
runnerScaleSetName: arc-runner-set

# GitHub App authentication
# Reference existing secret created by ExternalSecret
# The secret 'controller-manager' in arc-runners namespace contains:
# - github_app_id
# - github_app_installation_id
# - github_app_private_key
githubConfigSecret: controller-manager

# Controller service account configuration
# Explicitly set to avoid lookup issues during Helm template rendering
# Service account name matches the Helm release name (ArgoCD application name)
controllerServiceAccount:
  name: infra-arc-controller  # Helm release name from ArgoCD application
  namespace: arc-systems  # Controller namespace

# Runner scale set configuration
autoscalingRunnerSet:
  # Runner labels (must match runs-on in workflows)
  runnerLabels:
    - self-hosted
    - linux
    - arc-runner-set
  
  # Runner resources
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  # Docker configuration for container jobs
  dockerdWithinRunnerContainer: true
  dockerEnabled: true

# Autoscaling configuration (at root level, not under autoscalingRunnerSet)
minRunners: 1
maxRunners: 3

# Container mode - use dind (Docker-in-Docker) for container jobs
containerMode:
  type: dind

# Template specification for runner pods
template:
  spec:
    # Security context for runner pods
    # Note: Init containers need root access for volume setup
    # The chart will set appropriate security contexts for dind containers
    # We only set fsGroup to ensure volumes have correct permissions
    # Init containers will run as root (default), runner container will inherit from chart defaults
    securityContext:
      fsGroup: 1000

# Namespace override
namespaceOverride: arc-runners

