# GitHub Actions Runner Scale Set Helm Chart Values
# Deploy ARC runner scale set to arc-runners namespace
# Based on: https://docs.github.com/en/actions/tutorials/use-actions-runner-controller/quickstart

# GitHub configuration - repository-level (required for personal accounts)
githubConfigUrl: "https://github.com/amerenda/amerenda-k3s"

# GitHub App authentication
# Reference existing secret created by ExternalSecret
# The secret 'controller-manager' in arc-runners namespace contains:
# - github_app_id
# - github_app_installation_id
# - github_app_private_key
githubConfigSecret: controller-manager

# Controller service account configuration
# Explicitly reference the controller service account since we're using the older controller chart
controllerServiceAccount:
  name: arc-controller
  namespace: arc-systems

# Runner scale set configuration
autoscalingRunnerSet:
  # Installation name (used as runs-on in workflows)
  name: arc-runner-set
  
  # Runner labels (must match runs-on in workflows)
  runnerLabels:
    - self-hosted
    - linux
    - arc-runner-set
  
  # Autoscaling configuration
  minReplicas: 1
  maxReplicas: 3
  
  # Runner resources
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  # Docker configuration for container jobs
  dockerdWithinRunnerContainer: true
  dockerEnabled: true
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

# Namespace override
namespaceOverride: arc-runners

