# homeassistant.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: America/New_York
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ha-config-rpi5-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-rpi5
  local:
    path: /mnt/k8s/homeassistant/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["rpi5-0"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: home-assistant
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-rpi5
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  type: LoadBalancer
  ports:
  - port: 8123
    targetPort: 8123
  selector:
    app: homeassistant


