apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-secrets
  namespace: home-assistant
type: Opaque
stringData:
  secrets.yaml: |
    eufy_username: "${EUFY_USERNAME}"
    eufy_password: "${EUFY_PASSWORD}"
