apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-admin
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: pihole-admin
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: pihole-admin
      property: password
