apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth-key
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: tailscale-auth-key
    creationPolicy: Owner
  data:
  - secretKey: authkey
    remoteRef:
      key: tailscale-auth-key
      property: authkey

