alias: Alex - AC Auto Cool (Away)
mode: restart
triggers:
  - trigger: numeric_state
    entity_id: climate.midea_ac
    attribute: current_temperature
    above: 30
    for: "00:05:00"
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: person.alex_merenda
        state: "home"
  - condition: template
    value_template: "{{ state_attr('climate.midea_ac','hvac_mode') != 'cool' }}"
actions:
  - action: climate.set_hvac_mode
    target: { entity_id: climate.midea_ac }
    data: { hvac_mode: cool }
  - action: climate.set_temperature
    target: { entity_id: climate.midea_ac }
    data: { temperature: 27 }
