alias: Alex - Reolink Pet Snapshot (Away)
mode: queued
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.living_room_animal
      - binary_sensor.bedroom_animal
    from: "off"
    to: "on"
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: person.alex_merenda
        state: "home"
variables:
  CAM_MAP: >
    {{
      {
        'binary_sensor.living_room_animal':
          {'camera': 'camera.living_room_fluent', 'room':'Living Room','slug':'living_room'},
        'binary_sensor.bedroom_animal':
          {'camera': 'camera.bedroom_fluent',     'room':'Bedroom',    'slug':'bedroom'}
      }
    }}
  cam: "{{ CAM_MAP[trigger.entity_id]['camera'] }}"
  room: "{{ CAM_MAP[trigger.entity_id]['room'] }}"
  slug: "{{ CAM_MAP[trigger.entity_id]['slug'] }}"
  path: "/config/www/pets/{{ slug }}.jpg"
  url: "/local/pets/{{ slug }}.jpg"
actions:
  - action: camera.snapshot
    target: { entity_id: "{{ cam }}" }
    data:
      filename: "{{ path }}"
