alias: Alex - Night Lighting on Toggle
mode: parallel
triggers:
  - trigger: state
    entity_id:
      - light.living_room
      - light.bathroom
      - light.bedroom
      - light.hallway
      - light.kitchen
    from: "off"
    to: "on"
  - trigger: time
    at: "06:00:00"
variables:
  is_past_cutoff: >
    {% set wd = now().weekday() %}  {# Mon=0..Sun=6 #}
    {% set current_hour = now().hour %}
    {% if wd in [4,5] %}
      {{ current_hour >= 1 or current_hour < 6 }}
    {% else %}
      {{ current_hour >= 23 or current_hour < 6 }}
    {% endif %}
  room_scenes:
    light.living_room: scene.living_room_nightlight
    light.bathroom: scene.bathroom_nightlight
    light.bedroom: scene.bedroom_nightlight
    light.hallway: scene.hallway_nightlight
    light.kitchen: scene.kitchen_nightlight
  room_scene: "{{ room_scenes[trigger.entity_id] }}"
  energize_scenes:
    light.living_room: scene.living_room_energize
    light.bathroom: scene.bathroom_energize
    light.bedroom: scene.bedroom_energize
    light.hallway: scene.hallway_energize
    light.kitchen: scene.kitchen_energize
  energize_scene: "{{ energize_scenes[trigger.entity_id] }}"
actions:
  - choose:
      - conditions: 
          - condition: template
            value_template: "{{ trigger.platform == 'time' }}"
        sequence:
          - action: scene.turn_on
            target: { entity_id: "{{ energize_scene }}" }
      - conditions: 
          - condition: template
            value_template: "{{ trigger.platform == 'state' and is_past_cutoff }}"
        sequence:
          - action: scene.turn_on
            target: { entity_id: "{{ room_scene }}" }
