alias: Alex - AC Cool Off (Hysteresis)
mode: restart
triggers:
  - trigger: numeric_state
    entity_id: climate.midea_ac
    attribute: current_temperature
    below: 23
    for: "00:03:00"
conditions:
  - condition: template
    value_template: "{{ is_state_attr('climate.midea_ac','hvac_mode','cool') }}"
actions:
  - action: climate.set_hvac_mode
    target: { entity_id: climate.midea_ac }
    data: { hvac_mode: "off" }
