apiVersion: v1
kind: ConfigMap
metadata:
  name: eufy-human-detection-automation
  namespace: home-assistant
data:
  human-detection-automation.yaml: |
    # Human Detection Automation
    # Updates the "Event Image" on the home page dashboard when a human is detected
    
    - alias: "Human Detected - Living Room"
      description: "Updates event image when human detected in living room"
      trigger:
        - platform: state
          entity_id: 
            - camera.living_room
            - select.living_room_motion_detection_type
          to: 'on'
          for:
            seconds: 2
      action:
        - service: camera.snapshot
          target:
            device_id: add2baf8e9746e2f87ff5acfdc9d5541
          data:
            filename: '/config/www/event_image.jpg'
        - service: input_text.set_value
          entity_id: input_text.event_image_timestamp
          data:
            value: '{{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
        - service: input_text.set_value
          entity_id: input_text.event_image_location
          data:
            value: 'Living Room'
        - service: notify.mobile_app_pixel_9_pro_xl
          data:
            title: '👤 Human Detected in Living Room'
            message: 'Human detected in living room at {{ now().strftime("%H:%M:%S") }}'
            data:
              channel: 'Human Detection'
              importance: 'high'
    
    - alias: "Human Detected - Bedroom"
      description: "Updates event image when human detected in bedroom"
      trigger:
        - platform: state
          entity_id: 
            - camera.bedroom
            - select.bedroom_motion_detection_type
          to: 'on'
          for:
            seconds: 2
      action:
        - service: camera.snapshot
          target:
            device_id: cee1fb8e14d6c17e39b45beb672f677c
          data:
            filename: '/config/www/event_image.jpg'
        - service: input_text.set_value
          entity_id: input_text.event_image_timestamp
          data:
            value: '{{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
        - service: input_text.set_value
          entity_id: input_text.event_image_location
          data:
            value: 'Bedroom'
        - service: notify.mobile_app_pixel_9_pro_xl
          data:
            title: '👤 Human Detected in Bedroom'
            message: 'Human detected in bedroom at {{ now().strftime("%H:%M:%S") }}'
            data:
              channel: 'Human Detection'
              importance: 'high'

