apiVersion: v1
kind: ConfigMap
metadata:
  name: eufy-pet-detection-automation
  namespace: home-assistant
data:
  pet-detection-automation.yaml: |
    # Pet Detection Automation
    # Sends push notification with image preview when a pet is detected
    
    - alias: "Pet Detected - Living Room"
      description: "Sends notification when pet detected in living room"
      trigger:
        - platform: state
          entity_id: 
            - camera.living_room
            - select.living_room_motion_detection_type
          to: 'on'
          for:
            seconds: 2
      action:
        - service: camera.snapshot
          target:
            device_id: add2baf8e9746e2f87ff5acfdc9d5541
          data:
            filename: '/config/www/pet_detection_living_room_{{ now().strftime("%Y%m%d_%H%M%S") }}.jpg'
        - service: notify.mobile_app_pixel_9_pro_xl
          data:
            title: '🐾 Pet Detected in Living Room!'
            message: 'Pet detected in living room at {{ now().strftime("%H:%M:%S") }}'
            data:
              channel: 'Pet Detection'
              importance: 'high'
    
    - alias: "Pet Detected - Bedroom"
      description: "Sends notification when pet detected in bedroom"
      trigger:
        - platform: state
          entity_id: 
            - camera.bedroom
            - select.bedroom_motion_detection_type
          to: 'on'
          for:
            seconds: 2
      action:
        - service: camera.snapshot
          target:
            device_id: cee1fb8e14d6c17e39b45beb672f677c
          data:
            filename: '/config/www/pet_detection_bedroom_{{ now().strftime("%Y%m%d_%H%M%S") }}.jpg'
        - service: notify.mobile_app_pixel_9_pro_xl
          data:
            title: '🐾 Pet Detected in Bedroom!'
            message: 'Pet detected in bedroom at {{ now().strftime("%H:%M:%S") }}'
            data:
              channel: 'Pet Detection'
              importance: 'high'
    
    - alias: "Pet Detection - Cleanup Old Images"
      description: "Cleans up old pet detection images to save space"
      trigger:
        - platform: time
          at: "02:00:00"
      action:
        - service: shell_command.cleanup_pet_images
          data: {}

