# Default Time-Based Scene Schedule Configuration
# This file defines the default schedule for all rooms
# Can be overridden per room in individual automation files

default_schedule:
  # Schedule 1: Morning (06:00-09:00)
  schedule_1:
    start_time: "06:00"
    end_time: "09:00"
    scene_suffix: "energize"  # Will be prefixed with room name
  
  # Schedule 2: Day (09:00-17:00)
  schedule_2:
    start_time: "09:00"
    end_time: "17:00"
    scene_suffix: "concentrate"
  
  # Schedule 3: Evening (17:00-21:00)
  schedule_3:
    start_time: "17:00"
    end_time: "21:00"
    scene_suffix: "relax"
  
  # Schedule 4: Night (21:00-23:00)
  schedule_4:
    start_time: "21:00"
    end_time: "23:00"
    scene_suffix: "nightlight"
  
  # Schedule 5: Late Night (23:00-06:00)
  schedule_5:
    start_time: "23:00"
    end_time: "06:00"
    scene_suffix: "nightlight"
  
  # Default fallback scene
  default_scene_suffix: "relax"

# Room-specific overrides (optional)
room_overrides:
  # Example: Kitchen might have different morning time
  # kitchen:
  #   schedule_1:
  #     start_time: "05:30"
  #     end_time: "08:30"
  #     scene_suffix: "energize"
