input_datetime:
  living_room_schedule_1_start:
    name: "Living Room Morning Start"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  living_room_schedule_1_end:
    name: "Living Room Morning End"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  living_room_schedule_2_start:
    name: "Living Room Day Start"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  living_room_schedule_2_end:
    name: "Living Room Day End"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  living_room_schedule_3_start:
    name: "Living Room Evening Start"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  living_room_schedule_3_end:
    name: "Living Room Evening End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  living_room_schedule_4_start:
    name: "Living Room Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  living_room_schedule_4_end:
    name: "Living Room Night End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  living_room_schedule_5_start:
    name: "Living Room Late Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  living_room_schedule_5_end:
    name: "Living Room Late Night End"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  kitchen_schedule_1_start:
    name: "Kitchen Morning Start"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  kitchen_schedule_1_end:
    name: "Kitchen Morning End"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  kitchen_schedule_2_start:
    name: "Kitchen Day Start"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  kitchen_schedule_2_end:
    name: "Kitchen Day End"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  kitchen_schedule_3_start:
    name: "Kitchen Evening Start"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  kitchen_schedule_3_end:
    name: "Kitchen Evening End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  kitchen_schedule_4_start:
    name: "Kitchen Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  kitchen_schedule_4_end:
    name: "Kitchen Night End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  kitchen_schedule_5_start:
    name: "Kitchen Late Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  kitchen_schedule_5_end:
    name: "Kitchen Late Night End"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  bedroom_schedule_1_start:
    name: "Bedroom Morning Start"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  bedroom_schedule_1_end:
    name: "Bedroom Morning End"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  bedroom_schedule_2_start:
    name: "Bedroom Day Start"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  bedroom_schedule_2_end:
    name: "Bedroom Day End"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  bedroom_schedule_3_start:
    name: "Bedroom Evening Start"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  bedroom_schedule_3_end:
    name: "Bedroom Evening End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  bedroom_schedule_4_start:
    name: "Bedroom Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  bedroom_schedule_4_end:
    name: "Bedroom Night End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  bedroom_schedule_5_start:
    name: "Bedroom Late Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  bedroom_schedule_5_end:
    name: "Bedroom Late Night End"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  bathroom_schedule_1_start:
    name: "Bathroom Morning Start"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  bathroom_schedule_1_end:
    name: "Bathroom Morning End"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  bathroom_schedule_2_start:
    name: "Bathroom Day Start"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  bathroom_schedule_2_end:
    name: "Bathroom Day End"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  bathroom_schedule_3_start:
    name: "Bathroom Evening Start"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  bathroom_schedule_3_end:
    name: "Bathroom Evening End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  bathroom_schedule_4_start:
    name: "Bathroom Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  bathroom_schedule_4_end:
    name: "Bathroom Night End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  bathroom_schedule_5_start:
    name: "Bathroom Late Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  bathroom_schedule_5_end:
    name: "Bathroom Late Night End"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  hallway_schedule_1_start:
    name: "Hallway Morning Start"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

  hallway_schedule_1_end:
    name: "Hallway Morning End"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  hallway_schedule_2_start:
    name: "Hallway Day Start"
    icon: mdi:weather-sunny
    has_time: true
    has_date: false
    initial: "09:00"

  hallway_schedule_2_end:
    name: "Hallway Day End"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  hallway_schedule_3_start:
    name: "Hallway Evening Start"
    icon: mdi:weather-sunset
    has_time: true
    has_date: false
    initial: "17:00"

  hallway_schedule_3_end:
    name: "Hallway Evening End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  hallway_schedule_4_start:
    name: "Hallway Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "21:00"

  hallway_schedule_4_end:
    name: "Hallway Night End"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  hallway_schedule_5_start:
    name: "Hallway Late Night Start"
    icon: mdi:weather-night
    has_time: true
    has_date: false
    initial: "23:00"

  hallway_schedule_5_end:
    name: "Hallway Late Night End"
    icon: mdi:weather-sunrise
    has_time: true
    has_date: false
    initial: "06:00"

