# Dashboard-editable schedule configuration
# These input helpers can be edited from the Home Assistant dashboard

# Global schedule enable/disable
input_boolean:
  time_schedule_enabled:
    name: "Enable Time-Based Scenes"
    icon: mdi:clock-outline
    initial: true

# Schedule 1: Morning
input_time:
  schedule_1_start:
    name: "Morning Start Time"
    icon: mdi:weather-sunrise
    initial: "06:00"
  
  schedule_1_end:
    name: "Morning End Time"
    icon: mdi:weather-sunny
    initial: "09:00"

# Schedule 2: Day
input_time:
  schedule_2_start:
    name: "Day Start Time"
    icon: mdi:weather-sunny
    initial: "09:00"
  
  schedule_2_end:
    name: "Day End Time"
    icon: mdi:weather-sunset
    initial: "17:00"

# Schedule 3: Evening
input_time:
  schedule_3_start:
    name: "Evening Start Time"
    icon: mdi:weather-sunset
    initial: "17:00"
  
  schedule_3_end:
    name: "Evening End Time"
    icon: mdi:weather-night
    initial: "21:00"

# Schedule 4: Night
input_time:
  schedule_4_start:
    name: "Night Start Time"
    icon: mdi:weather-night
    initial: "21:00"
  
  schedule_4_end:
    name: "Night End Time"
    icon: mdi:weather-night
    initial: "23:00"

# Schedule 5: Late Night
input_time:
  schedule_5_start:
    name: "Late Night Start Time"
    icon: mdi:weather-night
    initial: "23:00"
  
  schedule_5_end:
    name: "Late Night End Time"
    icon: mdi:weather-sunrise
    initial: "06:00"

# Scene selectors for each schedule
input_select:
  schedule_1_scene:
    name: "Morning Scene"
    icon: mdi:weather-sunrise
    options:
      - "energize"
      - "concentrate"
      - "relax"
      - "nightlight"
      - "read"
      - "dimmed"
    initial: "energize"
  
  schedule_2_scene:
    name: "Day Scene"
    icon: mdi:weather-sunny
    options:
      - "energize"
      - "concentrate"
      - "relax"
      - "nightlight"
      - "read"
      - "dimmed"
    initial: "concentrate"
  
  schedule_3_scene:
    name: "Evening Scene"
    icon: mdi:weather-sunset
    options:
      - "energize"
      - "concentrate"
      - "relax"
      - "nightlight"
      - "read"
      - "dimmed"
    initial: "relax"
  
  schedule_4_scene:
    name: "Night Scene"
    icon: mdi:weather-night
    options:
      - "energize"
      - "concentrate"
      - "relax"
      - "nightlight"
      - "read"
      - "dimmed"
    initial: "nightlight"
  
  schedule_5_scene:
    name: "Late Night Scene"
    icon: mdi:weather-night
    options:
      - "energize"
      - "concentrate"
      - "relax"
      - "nightlight"
      - "read"
      - "dimmed"
    initial: "nightlight"
  
  default_scene:
    name: "Default Scene"
    icon: mdi:lightbulb
    options:
      - "energize"
      - "concentrate"
      - "relax"
      - "nightlight"
      - "read"
      - "dimmed"
    initial: "relax"
