blueprint:
  name: "Room Schedule Configuration"
  description: "Creates per-room schedule input helpers for time-based scene selection"
  domain: automation
  input:
    room_name:
      name: "Room Name"
      description: "Name of the room (e.g., living_room, kitchen, bedroom)"
      selector:
        text:
    room_display_name:
      name: "Room Display Name"
      description: "Display name for the room (e.g., Living Room, Kitchen, Bedroom)"
      selector:
        text:
    enable_schedule:
      name: "Enable Schedule for Room"
      description: "Whether to enable time-based scheduling for this room"
      default: true
      selector:
        boolean:
    morning_start:
      name: "Morning Start Time"
      description: "Start time for morning schedule"
      default: "06:00"
      selector:
        time:
    morning_end:
      name: "Morning End Time"
      description: "End time for morning schedule"
      default: "09:00"
      selector:
        time:
    morning_scene:
      name: "Morning Scene Type"
      description: "Scene type for morning period"
      default: "energize"
      selector:
        select:
          options:
            - "energize"
            - "concentrate"
            - "relax"
            - "nightlight"
            - "read"
            - "dimmed"
            - "custom"
    morning_custom_scene:
      name: "Morning Custom Scene"
      description: "Custom scene name for morning period (only used if Morning Scene Type is 'custom')"
      default: ""
      selector:
        text:
    day_start:
      name: "Day Start Time"
      description: "Start time for day schedule"
      default: "09:00"
      selector:
        time:
    day_end:
      name: "Day End Time"
      description: "End time for day schedule"
      default: "17:00"
      selector:
        time:
    day_scene:
      name: "Day Scene Type"
      description: "Scene type for day period"
      default: "concentrate"
      selector:
        select:
          options:
            - "energize"
            - "concentrate"
            - "relax"
            - "nightlight"
            - "read"
            - "dimmed"
            - "custom"
    day_custom_scene:
      name: "Day Custom Scene"
      description: "Custom scene name for day period (only used if Day Scene Type is 'custom')"
      default: ""
      selector:
        text:
    evening_start:
      name: "Evening Start Time"
      description: "Start time for evening schedule"
      default: "17:00"
      selector:
        time:
    evening_end:
      name: "Evening End Time"
      description: "End time for evening schedule"
      default: "21:00"
      selector:
        time:
    evening_scene:
      name: "Evening Scene Type"
      description: "Scene type for evening period"
      default: "relax"
      selector:
        select:
          options:
            - "energize"
            - "concentrate"
            - "relax"
            - "nightlight"
            - "read"
            - "dimmed"
            - "custom"
    evening_custom_scene:
      name: "Evening Custom Scene"
      description: "Custom scene name for evening period (only used if Evening Scene Type is 'custom')"
      default: ""
      selector:
        text:
    night_start:
      name: "Night Start Time"
      description: "Start time for night schedule"
      default: "21:00"
      selector:
        time:
    night_end:
      name: "Night End Time"
      description: "End time for night schedule"
      default: "23:00"
      selector:
        time:
    night_scene:
      name: "Night Scene Type"
      description: "Scene type for night period"
      default: "nightlight"
      selector:
        select:
          options:
            - "energize"
            - "concentrate"
            - "relax"
            - "nightlight"
            - "read"
            - "dimmed"
            - "custom"
    night_custom_scene:
      name: "Night Custom Scene"
      description: "Custom scene name for night period (only used if Night Scene Type is 'custom')"
      default: ""
      selector:
        text:
    late_night_start:
      name: "Late Night Start Time"
      description: "Start time for late night schedule"
      default: "23:00"
      selector:
        time:
    late_night_end:
      name: "Late Night End Time"
      description: "End time for late night schedule"
      default: "06:00"
      selector:
        time:
    late_night_scene:
      name: "Late Night Scene Type"
      description: "Scene type for late night period"
      default: "nightlight"
      selector:
        select:
          options:
            - "energize"
            - "concentrate"
            - "relax"
            - "nightlight"
            - "read"
            - "dimmed"
            - "custom"
    late_night_custom_scene:
      name: "Late Night Custom Scene"
      description: "Custom scene name for late night period (only used if Late Night Scene Type is 'custom')"
      default: ""
      selector:
        text:
    default_scene:
      name: "Default Scene Type"
      description: "Default scene type when schedule is disabled"
      default: "relax"
      selector:
        select:
          options:
            - "energize"
            - "concentrate"
            - "relax"
            - "nightlight"
            - "read"
            - "dimmed"
            - "custom"
    default_custom_scene:
      name: "Default Custom Scene"
      description: "Custom scene name for default (only used if Default Scene Type is 'custom')"
      default: ""
      selector:
        text:

# This blueprint doesn't create an automation, it's used to generate input helpers
# The actual automation logic is handled by the switch control blueprint
