apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-lb
  namespace: longhorn-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "longhorn"
    external-dns.alpha.kubernetes.io/hostname: longhorn.amer.local,longhorn.amer.home
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.20.243
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: longhorn-ui
