apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mongo-credentials
  namespace: unifi-network-application
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretstore
    kind: ClusterSecretStore
  target:
    name: unifi-mongo-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: unifi-mongo-credentials
      property: password

