# External DNS Helm Chart Values
# Official external-dns chart configuration for BIND9 integration

# Replica count
replicaCount: 1

# Service account configuration
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Service monitor for Prometheus
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# External DNS configuration
provider:
  name: rfc2136

# Extra arguments for RFC2136 provider
extraArgs:
  - --rfc2136-host=bind9.default.svc.cluster.local
  - --rfc2136-port=53
  - --rfc2136-zone=amer.home
  - --rfc2136-tsig-secret-alg=hmac-sha256
  - --rfc2136-tsig-axfr
  - --registry=txt
  - --txt-owner-id=external-dns

# Environment variables for TSIG secret
env:
  - name: "EXTERNAL_DNS_RFC2136_TSIG_SECRET"
    valueFrom:
      secretKeyRef:
        name: bind9-tsig
        key: key.conf
  - name: "EXTERNAL_DNS_RFC2136_TSIG_KEYNAME"
    value: "externaldns-key."

# Domain filters
domainFilters:
  - amer.home
# Exclude domains
excludeDomains: []

# DNS record types to manage
sources:
  - service

# Policy for DNS record management
policy: upsert-only

# Additional optimization settings
minEventSyncInterval: 1m

# TXT record configuration
txtOwnerId: "external-dns"
txtPrefix: ""

# Log level
logLevel: info
logFormat: text
