apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eufy-ws-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

