---
# Raspberry Pi 5 k3s + Longhorn Node Preparation Playbook
# This playbook prepares Raspberry Pi nodes for k3s cluster with Longhorn storage
# Run with: ansible-playbook -i inventory.ini setup-rpi.yml

- name: Prepare Raspberry Pi 5 nodes for k3s + Longhorn cluster
  hosts: rpi
  become: yes
  gather_facts: yes
  tags: [bootstrap, longhorn, ssh]

  vars:
    # Ensure we have the target user defined
    target_user: "{{ target_user | default(ansible_user) }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: [packages]

    - name: Upgrade system packages (optional)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: do_upgrade == "yes"
      tags: [packages, upgrade]

    - name: Install base packages
      apt:
        name: "{{ base_packages }}"
        state: present
        update_cache: yes
      tags: [packages]

    - name: Enable and start iscsid service for Longhorn
      systemd:
        name: "{{ longhorn_iscsi_service }}"
        enabled: "{{ longhorn_iscsi_enable }}"
        state: started
        daemon_reload: yes
      tags: [longhorn, services]

    - name: Add kernel modules to /etc/modules
      lineinfile:
        path: /etc/modules
        line: "{{ item }}"
        state: present
        create: yes
      loop: "{{ kernel_modules }}"
      tags: [longhorn, kernel]

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop: "{{ kernel_modules }}"
      tags: [longhorn, kernel]

    - name: Configure timezone
      timezone:
        name: "{{ timezone }}"
      tags: [system]

    - name: Generate locale
      locale_gen:
        name: "{{ locale }}"
        state: present
      tags: [system]

    - name: Set system locale
      lineinfile:
        path: /etc/environment
        line: "LANG={{ locale }}"
        state: present
      tags: [system]

    - name: Verify iscsid service status
      systemd:
        name: "{{ longhorn_iscsi_service }}"
      register: iscsid_status
      tags: [longhorn, verification]

    - name: Check loaded kernel modules
      command: lsmod
      register: loaded_modules
      changed_when: false
      tags: [longhorn, verification]

    - name: Display node preparation summary
      debug:
        msg: |
          ========================================
          Node Preparation Summary for {{ inventory_hostname }}
          ========================================
          Host: {{ ansible_default_ipv4.address }}
          User: {{ target_user }}
          SSH Key: {{ admin_pubkey[:50] }}...
          iscsid Status: {{ iscsid_status.status.ActiveState }}
          Loaded Modules: {{ kernel_modules | join(', ') }}
          Packages Installed: {{ base_packages | length }} packages
          ========================================
      tags: [summary]

  handlers:
    - name: restart iscsid
      systemd:
        name: "{{ longhorn_iscsi_service }}"
        state: restarted
      when: longhorn_iscsi_enable | bool
