alias: "Alex - Update Last Significant Zone"
mode: queued
triggers:
  - trigger: state
    entity_id: device_tracker.pixel_9_pro_xl
    to: "home"
  - trigger: state
    entity_id: device_tracker.pixel_9_pro_xl
    to: "work"
  - trigger: homeassistant
    event: start
conditions:
  - condition: template
    value_template: "{{ states('device_tracker.pixel_9_pro_xl') in ['home', 'work'] }}"
actions:
  - action: input_text.set_value
    target:
      entity_id: input_text.alex_last_significant_zone
    data:
      value: "{{ states('device_tracker.pixel_9_pro_xl') }}"
