alias: "Alex - Update Last Significant Zone"
mode: single
triggers:
  - trigger: state
    entity_id: device_tracker.pixel_9_pro_xl
    to: "home"
    id: "home"
  - trigger: state
    entity_id: device_tracker.pixel_9_pro_xl
    to: "work"
    id: "work"
conditions: []
actions:
  - action: input_text.set_value
    target:
      entity_id: input_text.alex_last_significant_zone
    data:
      value: "{{ trigger.id }}"

