alias: "Guest - Camera Privacy (WiFi Disconnected)"
labels:
  - Security
  - Privacy
  - Guests
mode: "restart"
triggers:
  - trigger: "state"
    entity_id:
      - "group.guests"
    from: "home"
actions:
  - action: script.manage_camera_privacy
