alias: "Guest - Camera Privacy Home (WiFi Connected)"
mode: "restart"
triggers:
  - trigger: "state"
    entity_id:
      - "device_tracker.brayan_iphone"
      - "device_tracker.eirill_iphone"
    to: "home"
actions:
  - action: "light.turn_off"
    target:
      entity_id:
        - "light.bedroom_status_led"
        - "light.living_room_status_led"
  - action: "switch.turn_on"
    target:
      entity_id:
        - "switch.bedroom_privacy_mode"
        - "switch.living_room_privacy_mode"
