alias: "Guest - Camera Privacy Home (WiFi Connected)"
labels:
  - Security
  - Privacy
  - Guests
mode: "restart"
triggers:
  - trigger: "state"
    entity_id:
      - "group.guests"
    to: "home"
actions:
  - action: script.manage_camera_privacy
