alias: "Members - Camera Privacy (Home)"
icon: mdi:cctv-off
mode: "restart"
triggers:
  - trigger: "state"
    entity_id: "group.members"
    to: "home"
    from: "not_home"
actions:
  - action: script.manage_camera_privacy

