alias: "Pet - Water Fountain Alert"
labels:
  - Pets
  - Maintenance
  - Notifications
mode: single
triggers:
  - trigger: state
    entity_id: binary_sensor.eversweet_solo_2_water_level
    from: "on"
    to: "off"
    for:
      minutes: 5
  - trigger: state
    entity_id: switch.eversweet_solo_2_power
    to: "off"
    for:
      minutes: 5
  # Fallback: Run on startup to catch if it was already off
  - trigger: homeassistant
    event: start
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.eversweet_solo_2_water_level
        state: "off"
        for:
          minutes: 5
      - condition: state
        entity_id: switch.eversweet_solo_2_power
        state: "off"
        for:
          minutes: 5
actions:
  - action: notify.mobile_app_pixel_9_pro_xl
    data:
      title: "Water Fountain Alert"
      message: >
        {% if trigger.entity_id == 'binary_sensor.eversweet_solo_2_water_level' %}
          Water level is low! Refill needed.
        {% else %}
          Fountain power is OFF! Check connection.
        {% endif %}
      data:
        tag: "water-fountain-alert"
        importance: "high"
        sticky: true
  - action: persistent_notification.create
    data:
      title: "Water Fountain Alert"
      message: >
        {% if trigger.entity_id == 'binary_sensor.eversweet_solo_2_water_level' %}
          Water level is low! Refill needed.
        {% else %}
          Fountain power is OFF! Check connection.
        {% endif %}
      notification_id: "water_fountain_alert"
