name: Generate Home Assistant ConfigMaps

on:
  push:
    branches: [ main ]
    paths:
      - 'gitops/apps/home-assistant/configuration/**'
      - '.github/workflows/ha-generate-configmaps.yaml'

jobs:
  generate-configmaps:
    name: Generate ConfigMaps
    runs-on: arc-runner-set
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install jinja2-cli

      - name: Generate all ConfigMaps
        run: |
          cd gitops/apps/home-assistant/configuration
          chmod +x ./generate-configmaps.sh
          ./generate-configmaps.sh

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git add gitops/apps/home-assistant/*-configmap.yaml
          git commit -m "chore: auto-generate Home Assistant ConfigMaps

          Generated by GitHub Actions workflow on $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          Changes detected in configuration/ directory:
          - automations/
          - blueprints/
          - dashboards/
          - helpers/
          - scripts/"
          git push origin HEAD:main
